from django.utils.translation import gettext as _
# Generated by Django 5.1.6 on 2025-08-26 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=_("Producto"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("nombre"), models.CharField(max_length=100)),
                (_("descripcion"), models.TextField()),
                (_("clasificacion"), models.CharField(max_length=50)),
                (_("precio"), models.DecimalField(decimal_places=2, max_digits=10)),
                (_("imagen"), models.ImageField(upload_to=_("productos/"))),
                (_("cantidadDisp"), models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name=_("Administrador"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("idAdministrador"), models.CharField(max_length=20, unique=True)),
                (_("user"), models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name=_("CuentaCliente"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("direccionPedido"), models.CharField(max_length=200)),
                (_("metodoPago"), models.CharField(max_length=50)),
                (_("user"), models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name=_("Carrito"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("totalCarrito"), models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (_("cliente"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("tienda.cuentacliente"))),
            ],
        ),
        migrations.CreateModel(
            name=_("Pedido"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("fechaPedido"), models.DateField(auto_now_add=True)),
                (_("totalPedido"), models.DecimalField(decimal_places=2, max_digits=10)),
                (_("direccionPedido"), models.CharField(max_length=200)),
                (_("cliente"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("tienda.cuentacliente"))),
            ],
        ),
        migrations.CreateModel(
            name=_("Pago"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("cantidad"), models.DecimalField(decimal_places=2, max_digits=10)),
                (_("metodoPago"), models.CharField(max_length=50)),
                (_("pedido"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=_("pagos"), to=_("tienda.pedido"))),
            ],
        ),
        migrations.CreateModel(
            name=_("Favorito"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("cliente"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("tienda.cuentacliente"))),
                (_("productos"), models.ManyToManyField(to=_("tienda.producto"))),
            ],
        ),
        migrations.CreateModel(
            name=_("CarritoItem"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("cantidad"), models.PositiveIntegerField()),
                (_("carrito"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("tienda.carrito"))),
                (_("producto"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("tienda.producto"))),
            ],
        ),
        migrations.AddField(
            model_name=_("carrito"),
            name=_("productos"),
            field=models.ManyToManyField(through=_("tienda.CarritoItem"), to=_("tienda.producto")),
        ),
    ]