from django.utils.translation import gettext as _
# Generated by Django 5.1.6 on 2025-09-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (_("tienda"), _("0001_initial")),
    ]

    operations = [
        migrations.RemoveField(
            model_name=_("carrito"),
            name=_("cliente"),
        ),
        migrations.RemoveField(
            model_name=_("carrito"),
            name=_("productos"),
        ),
        migrations.RemoveField(
            model_name=_("carritoitem"),
            name=_("carrito"),
        ),
        migrations.RemoveField(
            model_name=_("carritoitem"),
            name=_("producto"),
        ),
        migrations.RemoveField(
            model_name=_("cuentacliente"),
            name=_("user"),
        ),
        migrations.RemoveField(
            model_name=_("favorito"),
            name=_("cliente"),
        ),
        migrations.RemoveField(
            model_name=_("pedido"),
            name=_("cliente"),
        ),
        migrations.RemoveField(
            model_name=_("favorito"),
            name=_("productos"),
        ),
        migrations.RemoveField(
            model_name=_("pago"),
            name=_("pedido"),
        ),
        migrations.DeleteModel(
            name=_("Administrador"),
        ),
        migrations.DeleteModel(
            name=_("Carrito"),
        ),
        migrations.DeleteModel(
            name=_("CarritoItem"),
        ),
        migrations.DeleteModel(
            name=_("CuentaCliente"),
        ),
        migrations.DeleteModel(
            name=_("Favorito"),
        ),
        migrations.DeleteModel(
            name=_("Producto"),
        ),
        migrations.DeleteModel(
            name=_("Pago"),
        ),
        migrations.DeleteModel(
            name=_("Pedido"),
        ),
    ]