# Generated by Django 5.1.6 on 2025-09-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='cuentacliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
        migrations.DeleteModel(
            name='CuentaCliente',
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
