from django.utils.translation import gettext as _
# Generated by Django 5.1.6 on 2025-09-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (_("clientes"), _("0001_initial")),
    ]

    operations = [
        migrations.CreateModel(
            name=_("ChatbotLog"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("pregunta"), models.TextField()),
                (_("respuesta"), models.TextField()),
                (_("fecha"), models.DateTimeField(auto_now_add=True)),
                (_("cliente"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("clientes.cuentacliente"))),
            ],
        ),
    ]