from django.utils.translation import gettext as _
# Generated by Django 5.1.6 on 2025-09-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (_("chatbot"), _("0001_initial")),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=_("Conversation"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("title"), models.CharField(blank=True, max_length=200)),
                (_("created_at"), models.DateTimeField(auto_now_add=True)),
                (_("updated_at"), models.DateTimeField(auto_now=True)),
                (_("user"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=_("conversations"), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name=_("Message"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("role"), models.CharField(choices=[(_("system"), _("system")), (_("user"), _("user")), (_("assistant"), _("assistant"))], max_length=10)),
                (_("content"), models.TextField()),
                (_("meta"), models.JSONField(blank=True, default=dict)),
                (_("created_at"), models.DateTimeField(auto_now_add=True)),
                (_("conversation"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=_("messages"), to=_("chatbot.conversation"))),
            ],
            options={
                _("ordering"): [_("created_at")],
            },
        ),
        migrations.DeleteModel(
            name=_("ChatbotLog"),
        ),
    ]