from django.utils.translation import gettext as _
# Generated by Django 5.1.6 on 2025-09-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (_("clientes"), _("0001_initial")),
    ]

    operations = [
        migrations.CreateModel(
            name=_("Pedido"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("fechaPedido"), models.DateField(auto_now_add=True)),
                (_("totalPedido"), models.DecimalField(decimal_places=2, max_digits=10)),
                (_("direccionPedido"), models.CharField(max_length=200)),
                (_("cliente"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("clientes.cuentacliente"))),
            ],
        ),
        migrations.CreateModel(
            name=_("Pago"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("cantidad"), models.DecimalField(decimal_places=2, max_digits=10)),
                (_("metodoPago"), models.CharField(max_length=50)),
                (_("pedido"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=_("pagos"), to=_("pedidos.pedido"))),
            ],
        ),
    ]