# Generated by Django 5.2.4 on 2025-09-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
