from django.utils.translation import gettext as _
# Generated by Django 5.2.4 on 2025-09-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (_("pedidos"), _("0001_initial")),
    ]

    operations = [
        migrations.AddField(
            model_name=_("pedido"),
            name=_("estado"),
            field=models.CharField(choices=[(_("Pendiente"), _("Pendiente")), (_("Finalizado"), _("Finalizado")), (_("Cancelado"), _("Cancelado"))], default=_("Pendiente"), max_length=20),
        ),
    ]