from django.utils.translation import gettext as _
# Generated by Django 5.1.6 on 2025-09-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (_("clientes"), _("0001_initial")),
        (_("productos"), _("0001_initial")),
    ]

    operations = [
        migrations.CreateModel(
            name=_("Carrito"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("totalCarrito"), models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (_("cliente"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("clientes.cuentacliente"))),
            ],
        ),
        migrations.CreateModel(
            name=_("CarritoItem"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("cantidad"), models.PositiveIntegerField()),
                (_("carrito"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("carrito.carrito"))),
                (_("producto"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("productos.producto"))),
            ],
        ),
        migrations.AddField(
            model_name=_("carrito"),
            name=_("productos"),
            field=models.ManyToManyField(through=_("carrito.CarritoItem"), to=_("productos.producto")),
        ),
        migrations.CreateModel(
            name=_("Favorito"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("cliente"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=_("clientes.cuentacliente"))),
                (_("productos"), models.ManyToManyField(to=_("productos.producto"))),
            ],
        ),
    ]