from django.utils.translation import gettext as _
# Generated by Django 5.2.4 on 2025-09-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (_("carrito"), _("0001_initial")),
    ]

    operations = [
        migrations.RemoveField(
            model_name=_("carrito"),
            name=_("totalCarrito"),
        ),
        migrations.AlterField(
            model_name=_("carritoitem"),
            name=_("cantidad"),
            field=models.PositiveIntegerField(default=1),
        ),
    ]