from django.utils.translation import gettext as _
# Generated by Django 5.1.6 on 2025-09-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name=_("Producto"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("nombre"), models.CharField(max_length=100)),
                (_("descripcion"), models.TextField()),
                (_("clasificacion"), models.CharField(max_length=50)),
                (_("precio"), models.DecimalField(decimal_places=2, max_digits=10)),
                (_("imagen"), models.ImageField(upload_to=_("productos/"))),
                (_("cantidadDisp"), models.PositiveIntegerField()),
            ],
        ),
    ]