from django.utils.translation import gettext as _
# Generated by Django 5.1.6 on 2025-09-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (_("productos"), _("0001_initial")),
    ]

    operations = [
        migrations.AddField(
            model_name=_("producto"),
            name=_("activo"),
            field=models.BooleanField(default=True),
        ),
    ]