# Generated by Django 5.1.6 on 2025-11-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clasificacion_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='clasificacion_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
