from django.utils.translation import gettext as _
# Generated by Django 5.1.6 on 2025-09-07 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=_("Administrador"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("idAdministrador"), models.CharField(max_length=20, unique=True)),
                (_("user"), models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name=_("CuentaCliente"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("direccionPedido"), models.CharField(max_length=200)),
                (_("metodoPago"), models.CharField(max_length=50)),
                (_("user"), models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]