from django.utils.translation import gettext as _
# Generated by Django 5.2.4 on 2025-09-09 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (_("clientes"), _("0001_initial")),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=_("RegistroActividad"),
            fields=[
                (_("id"), models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_("ID"))),
                (_("tipo_actividad"), models.CharField(choices=[(_("CARRITO"), _("Añadió al carrito")), (_("FAVORITO"), _("Añadió a favoritos")), (_("PEDIDO"), _("Pedido realizado"))], max_length=20)),
                (_("detalles"), models.TextField(blank=True, null=True)),
                (_("fecha"), models.DateTimeField(auto_now_add=True)),
                (_("usuario"), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                _("verbose_name"): _("Registro de Actividad"),
                _("verbose_name_plural"): _("Registros de Actividad"),
                _("ordering"): [_("-fecha")],
            },
        ),
    ]